import type { Project } from "./types";

export const sampleProjects: Project[] = [
  {
    id: "1",
    title: "AuraRing Smart Health Tracker",
    title_ja: "AuraRing スマートヘルストラッカー",
    subtitle:
      "Medical-grade sleep and recovery tracking in a sleek titanium ring. 7-day battery, no subscription.",
    subtitle_ja:
      "チタン製リングに医療グレードの睡眠・回復トラッキング。7日間バッテリー、サブスク不要。",
    platform: "kickstarter",
    original_url: "https://www.kickstarter.com/projects/example/auraring",
    image_url: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80",
    raised_usd: 842_000,
    goal_usd: 50_000,
    backers: 12_450,
    category: "ヘルスケア",
    country: "USA",
    status: "ended",
    score: 95,
    offer_status: "未接触",
    japan_cf_checked: true,
    japan_cf_result: {
      checkedAt: new Date().toISOString(),
      query: "AuraRing",
      isJapanUnentered: true,
      sites: [
        { site: "makuake", found: false, url: "https://www.makuake.com/search/?search=AuraRing", query: "AuraRing" },
        { site: "greenfunding", found: false, url: "https://greenfunding.jp/search?q=AuraRing", query: "AuraRing" },
        { site: "campfire", found: false, url: "https://camp-fire.jp/search?q=AuraRing", query: "AuraRing" },
      ],
    },
    pse_ok: false,
    giteki_ok: false,
    maker_email: "hello@auraring.example",
    maker_website: "https://auraring.example",
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "2",
    title: "NeoBrew Portable Espresso Maker",
    title_ja: "NeoBrew ポータブルエスプレッソメーカー",
    subtitle:
      "Barista-quality espresso anywhere. USB-C rechargeable, 18-bar pressure, 90-second brew.",
    subtitle_ja:
      "どこでもバリスタ品質のエスプレッソ。USB-C充電、18気圧、90秒抽出。",
    platform: "indiegogo",
    original_url: "https://www.indiegogo.com/projects/example/neobrew",
    image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    raised_usd: 312_000,
    goal_usd: 30_000,
    backers: 4_820,
    category: "ガジェット",
    country: "Italy",
    status: "ended",
    score: 78,
    offer_status: "交渉中",
    japan_cf_checked: true,
    japan_cf_result: {
      checkedAt: new Date().toISOString(),
      query: "NeoBrew",
      isJapanUnentered: false,
      sites: [
        { site: "makuake", found: true, url: "https://www.makuake.com/search/?search=NeoBrew", query: "NeoBrew" },
        { site: "greenfunding", found: false, url: "https://greenfunding.jp/search?q=NeoBrew", query: "NeoBrew" },
        { site: "campfire", found: false, url: "https://camp-fire.jp/search?q=NeoBrew", query: "NeoBrew" },
      ],
    },
    pse_ok: true,
    giteki_ok: false,
    maker_email: "partners@neobrew.example",
    maker_website: "https://neobrew.example",
    created_at: "2026-05-28T00:00:00Z",
    updated_at: "2026-06-02T00:00:00Z",
  },
  {
    id: "3",
    title: "SkyFold Drone Backpack",
    title_ja: "SkyFold 折りたたみドローンバックパック",
    subtitle:
      "Foldable 4K drone that fits in your pocket. 45-min flight time, obstacle avoidance, 4K60.",
    subtitle_ja:
      "ポケットサイズに折りたためる4Kドローン。45分飛行、障害物回避、4K60撮影。",
    platform: "kickstarter",
    original_url: "https://www.kickstarter.com/projects/example/skyfold",
    image_url: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80",
    raised_usd: 1_240_000,
    goal_usd: 100_000,
    backers: 8_920,
    category: "Technology",
    country: "UK",
    status: "ended",
    score: 88,
    offer_status: "未接触",
    japan_cf_checked: false,
    japan_cf_result: null,
    pse_ok: false,
    giteki_ok: false,
    maker_email: null,
    maker_website: "https://skyfold.example",
    created_at: "2026-05-20T00:00:00Z",
    updated_at: "2026-05-20T00:00:00Z",
  },
  {
    id: "4",
    title: "ZenDesk AI Standing Desk",
    title_ja: "ZenDesk AIスタンディングデスク",
    subtitle:
      "AI-powered ergonomic desk that learns your posture habits. Silent dual motors, bamboo top.",
    subtitle_ja:
      "姿勢習慣を学習するAI搭載エルゴデスク。静音デュアルモーター、竹天板。",
    platform: "kickstarter",
    original_url: "https://www.kickstarter.com/projects/example/zendesk-desk",
    image_url: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80",
    raised_usd: 567_000,
    goal_usd: 80_000,
    backers: 2_340,
    category: "ガジェット",
    country: "Canada",
    status: "ended",
    score: 72,
    offer_status: "獲得済み",
    japan_cf_checked: true,
    japan_cf_result: {
      checkedAt: new Date().toISOString(),
      query: "ZenDesk",
      isJapanUnentered: true,
      sites: [
        { site: "makuake", found: false, url: "https://www.makuake.com/search/?search=ZenDesk", query: "ZenDesk" },
        { site: "greenfunding", found: false, url: "https://greenfunding.jp/search?q=ZenDesk", query: "ZenDesk" },
        { site: "campfire", found: false, url: "https://camp-fire.jp/search?q=ZenDesk", query: "ZenDesk" },
      ],
    },
    pse_ok: true,
    giteki_ok: true,
    maker_email: "sales@zendesk-desk.example",
    maker_website: "https://zendesk-desk.example",
    created_at: "2026-05-10T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
];

export { getDashboardStats } from "./dashboard-stats";
